package com.retailmind.api.application.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class InventoryInsightResponse {
    private String skuId;
    private String skuName;
    private int currentStock;
    private String riskLevel; // CRITICAL, HIGH, MEDIUM, LOW
    private String aiRecommendation; // Generated by Bedrock
}
