AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: RetailMind Java Spring Boot GenAI API
Globals:
  Function:
    Timeout: 30
    MemorySize: 1024
    Environment:
      Variables:
        JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
        SPRING_PROFILES_ACTIVE: prod
Resources:
  RetailMindApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-liypuefvc7eg/45dc6c4bb0a609828a086cb017a6ba0d
      Handler: com.retailmind.api.infrastructure.lambda.StreamLambdaHandler::handleRequest
      Runtime: java21
      Architectures:
      - x86_64
      Policies:
      - AmazonBedrockFullAccess
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      Events:
        RetailMindApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
Outputs:
  RetailMindApi:
    Description: API Gateway endpoint URL for Prod environment for RetailMind API
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
