import React, { useState } from 'react';
import {
    Menu, MenuItem, ListItemIcon, ListItemText, CircularProgress
} from '@mui/material';
import { PictureAsPdf, TableChart, Description } from '@mui/icons-material';
import type { InventoryInsightResponse } from '../services/api';

interface ExportReportsProps {
    anchorEl: HTMLElement | null;
    open: boolean;
    onClose: () => void;
    insights: InventoryInsightResponse[];
    storeId: string;
}

const ExportReports: React.FC<ExportReportsProps> = ({ anchorEl, open, onClose, insights, storeId }) => {
    const [exporting, setExporting] = useState(false);

    const exportToCSV = () => {
        setExporting(true);
        
        const headers = ['SKU Name', 'Current Stock', 'Risk Level', 'AI Recommendation'];
        const rows = insights.map(i => [
            i.skuName,
            i.currentStock.toString(),
            i.riskLevel,
            i.aiRecommendation.replace(/"/g, '""') // Escape quotes
        ]);

        const csv = [
            headers.join(','),
            ...rows.map(row => row.map(cell => `"${cell}"`).join(','))
        ].join('\n');

        const blob = new Blob([csv], { type: 'text/csv' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `retailmind_insights_store_${storeId}_${new Date().toISOString().split('T')[0]}.csv`;
        a.click();
        URL.revokeObjectURL(url);

        setTimeout(() => {
            setExporting(false);
            onClose();
        }, 500);
    };

    const exportToJSON = () => {
        setExporting(true);
        
        const data = {
            storeId,
            exportDate: new Date().toISOString(),
            totalSkus: insights.length,
            criticalCount: insights.filter(i => i.riskLevel === 'CRITICAL').length,
            highCount: insights.filter(i => i.riskLevel === 'HIGH').length,
            insights: insights
        };

        const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `retailmind_insights_store_${storeId}_${new Date().toISOString().split('T')[0]}.json`;
        a.click();
        URL.revokeObjectURL(url);

        setTimeout(() => {
            setExporting(false);
            onClose();
        }, 500);
    };

    const exportToPDF = () => {
        setExporting(true);
        
        // Create HTML for PDF
        const html = `
            <!DOCTYPE html>
            <html>
            <head>
                <title>RetailMind Insights Report</title>
                <style>
                    body { font-family: Arial, sans-serif; margin: 40px; }
                    h1 { color: #667eea; }
                    table { width: 100%; border-collapse: collapse; margin-top: 20px; }
                    th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
                    th { background-color: #667eea; color: white; }
                    .critical { color: #d32f2f; font-weight: bold; }
                    .high { color: #f57c00; font-weight: bold; }
                    .medium { color: #0288d1; }
                    .low { color: #388e3c; }
                </style>
            </head>
            <body>
                <h1>🛒 RetailMind - Inventory Intelligence Report</h1>
                <p><strong>Store ID:</strong> ${storeId}</p>
                <p><strong>Report Date:</strong> ${new Date().toLocaleString()}</p>
                <p><strong>Total SKUs:</strong> ${insights.length}</p>
                
                <table>
                    <thead>
                        <tr>
                            <th>SKU Name</th>
                            <th>Current Stock</th>
                            <th>Risk Level</th>
                            <th>AI Recommendation</th>
                        </tr>
                    </thead>
                    <tbody>
                        ${insights.map(i => `
                            <tr>
                                <td>${i.skuName}</td>
                                <td>${i.currentStock}</td>
                                <td class="${i.riskLevel.toLowerCase()}">${i.riskLevel}</td>
                                <td>${i.aiRecommendation}</td>
                            </tr>
                        `).join('')}
                    </tbody>
                </table>
                
                <p style="margin-top: 40px; color: #666; font-size: 12px;">
                    Generated by RetailMind AI - Powered by Amazon Bedrock
                </p>
            </body>
            </html>
        `;

        const blob = new Blob([html], { type: 'text/html' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `retailmind_report_store_${storeId}_${new Date().toISOString().split('T')[0]}.html`;
        a.click();
        URL.revokeObjectURL(url);

        setTimeout(() => {
            setExporting(false);
            onClose();
        }, 500);
    };

    return (
        <Menu
            anchorEl={anchorEl}
            open={open}
            onClose={onClose}
            anchorOrigin={{ vertical: 'bottom', horizontal: 'right' }}
            transformOrigin={{ vertical: 'top', horizontal: 'right' }}
        >
            <MenuItem onClick={exportToCSV} disabled={exporting || insights.length === 0}>
                <ListItemIcon>
                    {exporting ? <CircularProgress size={20} /> : <TableChart fontSize="small" />}
                </ListItemIcon>
                <ListItemText>Export as CSV</ListItemText>
            </MenuItem>
            <MenuItem onClick={exportToJSON} disabled={exporting || insights.length === 0}>
                <ListItemIcon>
                    {exporting ? <CircularProgress size={20} /> : <Description fontSize="small" />}
                </ListItemIcon>
                <ListItemText>Export as JSON</ListItemText>
            </MenuItem>
            <MenuItem onClick={exportToPDF} disabled={exporting || insights.length === 0}>
                <ListItemIcon>
                    {exporting ? <CircularProgress size={20} /> : <PictureAsPdf fontSize="small" />}
                </ListItemIcon>
                <ListItemText>Export as HTML Report</ListItemText>
            </MenuItem>
        </Menu>
    );
};

export default ExportReports;
